full_name = input("Enter your full name: ")
age = input("Enter your age: ")
faculty = input("Enter your faculty: ")
birth_date = input("Enter your birth date: ")
graduation_year = input("Enter your graduation year: ")

print("\nYour Information:")
print("Full Name:", full_name)
print("Age:", age)
print("Faculty:", faculty)
print("Birth Date:", birth_date)
print("Graduation Year:", graduation_year)
